### ISSUE TITLE
"add account" functionality

### ISSUE THREAD

**Issue by JanC** [futuretap/InAppSettingsKit#174]
Hi,
is it possible with InAppSettingsKit to configure (add, remove) a list of "accounts" in the same way the MailApp settings page does it? 

This means:
- an "account" is defined by a plist setting file
- a view showing a list of configured account
- "add / remove account" buttons

**Comment by rlaferla** [comment]
What's the status on this functionality?  Is it now possible to use it?  If so, how?  Is there an example?  Does it work only in-app or does it also work in the Settings app?

**Comment by JanC** [comment]
This functiomality was never used.

**Comment by rlaferla** [comment]
What's the best way to implement an editable list (add/remove/edit)?  I'm trying a custom view where the cell is a UITableView but is there a better way?

**Comment by JanC** [comment]
Well it depends. What is it that you want to do exactly?

**Comment by rlaferla** [comment]
Basically, manage a list of records (accounts) like what you did.  When you tap "Add Record", it adds a record to the list (table).   When you tap on a record, it takes you to the detail (to edit the values).  Also, some way to delete a record (could be from the list or a remove button on the detail.)

As for the underlying model, initially just the defaults store will suffice.  But it would be nice if I could use CoreData or some custom store for some or all of the fields.

**Comment by rlaferla** [comment]
I think this functionality should be part of the core InAppSettingsKit.  Ideally, it would be a new specifier: IASKTableViewSpecifier.  You would specify a plist file for the detail.  Each record would be numbered so that the defaults would be unique for each detail.  i.e.  record1.firstName, record1.lastName, record2.firstName, record2.lastName or some scheme like that.  The string "record" could even be part of the detail plist so that you could customize it.   eg.  <key>DetailIDPrefix></key><string>myrecord</string>

**Comment by rlaferla** [comment]
If this was part of the core IAK API, the developer would specify the table with IASKTableViewSpecifier along with an entry for the detail plist in the Root.plist.  The form for the detail would be in the detail plist.

e.g.

Root.plist:

```	   <?xml version="1.0" encoding="UTF-8"?>
	   <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
	   <plist version="1.0">
	   <dict>
	   	<key>PreferenceSpecifiers</key>
	   	<array>
		 <dict>
            <key>Title</key>
            <string>Users</string>
            <key>Type</key>
            <string>IASKTableViewSpecifier</string>
			<key>Detail</key>
			<string>UserDetail</string>
        </dict>
	</array>
	<key>StringsTable</key>
	<string>Root</string>
</dict>
</plist>
```		
		
		
		
		
UserDetail.plist:
		
```		<?xml version="1.0" encoding="UTF-8"?>
		<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
		<plist version="1.0">
		<dict>
			<key>Title</key>
			<string>DETAIL_TITLE</string>
			<key>StringsTable</key>
			<string>Root</string>
			<key>PreferenceSpecifiers</key>
			<array>

        <dict>
            <key>AutocapitalizationType</key>
            <string>None</string>
            <key>AutocorrectionType</key>
            <string>No</string>
            <key>DefaultValue</key>
            <string></string>
            <key>IsSecure</key>
            <false/>
            <key>Key</key>
            <string>name_preference</string>
            <key>KeyboardType</key>
            <string>Alphabet</string>
            <key>Title</key>
            <string>Username</string>
            <key>Type</key>
            <string>PSTextFieldSpecifier</string>
        </dict>
        <dict>
            <key>AutocapitalizationType</key>
            <string>None</string>
            <key>AutocorrectionType</key>
            <string>No</string>
            <key>DefaultValue</key>
            <string></string>
            <key>IsSecure</key>
            <true/>
            <key>Key</key>
            <string>name_preference</string>
            <key>KeyboardType</key>
            <string>Alphabet</string>
            <key>Title</key>
            <string>Password</string>
            <key>Type</key>
            <string>PSTextFieldSpecifier</string>
        </dict>

			</array>
		</dict>
		</plist>
```

**Comment by JanC** [comment]
Actually I'm working on a new library that allow to present this kind of settings. It does not use plist at all thought. It's still in development though. 
https://github.com/JanC/TASettings

I'll post a sample code on how you would use it for your use case

**Comment by futuretap** [comment]
@rlaferla that would be an interesting addition indeed. I'd suggest storing the records in a simple array type specified by the `Key` parameter in the master plist. Also I suggest naming it `IASKChildListSpecifier` and using the `File` parameter to specify the file of the child pane. Then we don't need `Detail` and `Prefix`.

So the specifier in the Root.plist would look like this:

    <dict>
        <key>Title</key>
        <string>Users</string>
        <key>Type</key>
        <string>IASKChildListSpecifier</string>
        <key>Key</key>
        <string>users</string>
        <key>File</key>
        <string>detail_username</string>
    </dict>

Would you be interested in contributing this feature?

**Comment by rlaferla** [comment]
Sure but we'll need to discuss it more.

**Comment by rlaferla** [comment]
Essentially, this is a master-detail design pattern.

MASTER

The master needs to display a list of records so it needs a title for each record.  That title could be a field from the detail or some combination.  e.g.  If you have a list of users, the title could be the "username" or it could be "Last Name, First Name" or something else.  To keep it simple, I suggest a single value from the detail in the initial implementation.

The master needs a title and description for the list.  In the "users" example, the title could be "Users" and the description is some optional information for the user of the app.

The list is initially empty but should contain a row or a button (design choice here) to allow adding a new record.  The title of that button should be configurable/localizable.  e.g.  "Add new user", "Add new device", etc...  Once there is data, the list displays those records.

```
<dict>
<key>Title</key>
<string>Users</string>
<key>Type</key>
<string>IASKChildListSpecifier</string>
<key>Key</key>
<string>users</string>
<key>File</key>
<string>userdetail</string>
<key>AddButtonTitle</key>
<string>ADD_USER_TITLE</string>
</dict>
```

DETAIL

The detail is a form that is specified in a plist file from the "File" key in the master plist.  e.g.  userdetail.plist  

There needs to be a button to delete the detail record.   I suggest making the color of the button text "red" to indicate a destructive action which is consistent with what the system settings uses.  When the delete button is pressed, a confirmation dialog should appear with a delete warning.  e.g. "Deleting this user will remove all data associated with it."

```

various fields in the detail such as username, password, etc...

<dict>
<key>DeleteButtonTitle</key>
<string>DELETE_USER_TITLE</string>
<key>DeleteWarningTitle</key>
<string>DELETE_USER_WARNING</string>
</dict>
```


ISSUES

What uniquely identifies each record so that editing/deleting work properly?  When and how does each the detail record get stored?  What (if any) notifications are sent when a record is added/deleted/modified?  How will this work with non-defaults data stores?  ie.  CoreData, file, etc...

**Comment by futuretap** [comment]
Thanks for the issues you raised.

- To specify the displayed field, I suggest `IASKChildKey`. In the above example this could be "compositeName", assuming this key is set in the details.
- Design-wise, I suggest using the keyboard settings dialog as our model for the master view:
  - Below the list is one cell with a custom label named `IASKChildListAddButtonTitle` that opens the detail view for a new record
  - Swipe to delete is supported and we simple use the default color and title for the delete button. This is standard UITableView behavior.
  - As long as there is at least one `IASKChildListSpecifier`, "Edit" is displayed as the right bar button item. This is standard UITableView behavior.
  - We may want to support changing the order (`IASKChildListReorderSupported` flag with default `YES`).
- I suggest using the Twitter system settings as our model for the detail view:
	- Two different layouts for create and update. This is probably the most flexible solution. We could reference them with `IASKChildListCreateFile` and `IASKChildListUpdateFile` (instead of the too ambiguous `File` I proposed before).
	- Create mode needs a `IASKChildListCreateButtonTitle` key. This sets the name of the create button. When tapping it, the account is actually created in the SettingsStore. We should consider adding a delegate callback `-(BOOL)shouldCreateAccountWithDictionary:(NSDictionary*)dictionary` to let the delegate validate the account before creating it.
	- The Create view controller is pushed, the Update view controller is presented modally with a Cancel and Done button.
	- For Update we might want to add the delegate callback `-(BOOL)shouldUpdateAccountWithDictionary:(NSDictionary*)dictionary` that is called on tapping `Done`.
  
- I'd omit the warning mechanism but instead add `IASKChildListDeleteSupported` (default `YES`) that enables delete on the master view controller. If a warning is needed, the developer can set this to `NO` and add a `IASKButtonSpecifier` in the update details to delete the account. This would be similar to Mail or Twitter accounts in the system settings. By overriding `
-tableView:willDisplayCell:forRowAtIndexPath:` the button title color can be set to red. (Alternatively we can add a `IASKButtonColor`.)
- To identify the record, we might get away with just the array index. Not sure, we might need to revisit this during implementation. Worst case, we'd have to add a `IASKChildListIdentifier` that is automatically populated with a UUID.

- The record will be saved on tapping "Create" or "Done" in the update layout.

Does that make sense? Did we forget any details?

**Comment by rlaferla** [comment]
We'll need to take a few passes on this but it's a good start.

-  I like the swipe to delete on the list.
-  I think having both a Create and Update file would be difficult to maintain for the developer.  There are just a few minor differences between the two and I think they would be better placed in the IASKChildListFile.

I guess we're I'm having some trouble is how this would work if the store was a database.  ie.  insert record then delete it if not used or insert record after user exits detail.    Related is the user interface behavior.  Users expect records to be automatically saved without a "Create" or "Save" or "Done" button.  Need to discuss this more.

**Comment by futuretap** [comment]
When you look at the Twitter settings for instance, Create and Update is quite different. Some fields are disabled or missing in Update, some fields are missing in Create. We could use our `-setHiddenKeys:animated:` mechanism for that but that would require publishing information about the current state so that the caller knows if Create or Update mode is active. Also it would require to duplicate keys that differ only in disabled state. Not very convenient either. That's why I came to the conclusion that it's probably easier and more straight-forward to use two entirely different layouts. It will also be much more flexible. Take the Keyboard settings, for instance. In Create, it presents a list of types, in Update it displays just the options for each type. Using dynamic key hiding for options depending on certain types, this even would be possible with IASK.

If we insert or update only on "Create" or "Done", this would work well with alternative stores. Also, the modal view controller UI suggests that nothing is stored until "Done" is tapped, since there's "Cancel", too. iOS uses this mode for Mail and Twitter, so users are already familiar with that.

I agree it's somewhat annoying if the state is not immediately saved, particularly in Update mode. We could of course change the UI to use a push in Update mode, too, and save changes directly. The only drawback I see is that a validation mechanism is not easily doable in this case since there's no definitive point in time where validation would occur.

I expect that the feature will be used in a lot of cases to manage remote accounts of some kind. This would involve some kind of validation in almost all cases, I assume. Also, without any validation of some kind, we could end up with empty records that look confusing in the master list layout.

One idea would be to use Push on Update and instant saving if no validation callback is defined, Modal presentation and save-after-validate otherwise. But that makes things more complicated and there are more code paths to test.

For Create I wouldn't change the save point since it's rather obvious that a "Create" button must be tapped in order to actually create the record.

**Comment by rlaferla** [comment]
How would storing/retrieving the data work exactly?  Each table view would have an array of records.  It seems that it could be stored as an array of dictionaries for the key in NSUserDefaults.  Thoughts?

"The accounts are stored in an array of the supplied IASKSettingStore. The key of this array is the key supplied in the plist (MyAccountsKey)"

**Comment by rlaferla** [comment]
Furthermore, if you have a list (table view) and then go to a detail record.  That detail record may also have 1 or more lists (tables).  How should it work?

**Comment by rlaferla** [comment]
![tablelist](https://cloud.githubusercontent.com/assets/1135694/9982550/39f8dc74-5fae-11e5-8f45-d6aa72e02af9.png)

**Comment by futuretap** [comment]
Indeed we need accessors for a child list array. I propose returning an array of `IASKChildSettingsStore` which is a subclass of `IASKAbstractSettingsStore` that doesn't actually save anything persistently but rather in a dictionary. Only when the update or create action is submitted, the array setter if the master settings store actually performs the save, for instance in `NSUserDefaults`.

This allows us to continue to use the same store interface for all element types in child controllers.

Nesting child lists shouldn't be a problem I guess. Only the setArray method needs to support nested arrays of `IASKChildSettingsStore` objects. However this is really an edge case. So should we encounter any issues with this, I'd be fine to forbid nesting.

**Comment by rlaferla** [comment]
What are your thoughts on where the controller (tableview delegate) should reside as there needs to be one per specifier?  The IASKSpecifierValuesViewController and IASKAppSettingsWebViewController controllers are different in that they are displayed on a separate scene.  I have been thinking that the table would be inline rather than on a separate full screen scene.  If it's to be inline (which I think is better), perhaps the controller could be in the SpecifierViewCell.

**Comment by futuretap** [comment]
For the master, I would include it in `IASKAppSettingsViewController` itself and integrate the account list into the standard tableView. Every `IASKChildListIdentifier` is one tableView section and every account is one row. So we have to catch the case in `-tableView:numberOfRowsInSection:` and the other datasource methods. The slave is a second instance of `IASKAppSettingsViewController`, just as for `PSChildPaneSpecifier`. Does that make sense?

**Comment by rlaferla** [comment]
I'll take a look.  My gut reaction is that it may make a mess of IASKAppSettingsViewController.  One way to address this is to create a child controller on IASKAppSettingsViewController that handles the datasource and delegate for the child list specifiers.  I think that would be cleaner.

**Comment by futuretap** [comment]
I'd strongly push for one tableView instead of a tableView in tableView architecture. This means we have only one tableView datasource and delegate. Of course, we could branch the child list case into separate methods and put them into a category.

**Comment by rlaferla** [comment]
Are you saying that the tableview appears on it's on scene/screen? i.e.  not inline

**Comment by futuretap** [comment]
No it should be integrated into the rest of the tableView e.g. I can have simple switched combined with one or multiple account lists, all in one tableView.

**Comment by rlaferla** [comment]
What are your reservations about a tableView in tableView architecture?  I'm assuming the child tableviews are not individually scrollable but that the fixed tableview is but a row in the master tableview.

**Comment by futuretap** [comment]
First you have to dynamically resize the outer tableView cell. Think about swipe to delete: the inner tableView shrinks dynamically and the outer tableView cell must synchronously resize. Then, there's only one Edit button in the navigation bar to switch the tableView in Edit mode. How could this even work with multiple tableViews? I don't think you can enable Edit mode in multiple tableViews simultaneously.

I think it's way easier to achieve a fluid UI with all animations working properly if we stay with just one tableView. Sure it's a bit more work to modify the datasource/delegate but the view part will be much easier.

Btw. we used the same approach when we added radio buttons.

**Comment by rlaferla** [comment]
I have a somewhat working prototype now - just to get a better understanding of the design issues.  There is no issue (that I can see) with multiple table views.  Delete seems to work.

![image](https://cloud.githubusercontent.com/assets/1135694/10008574/3122cbfa-609e-11e5-9dbb-f8706b23a3df.png)

**Comment by futuretap** [comment]
OK so it looks like two tableViews can be in Edit mode simultaneously. However, the outer tableView cell doesn't seem to be resized yet according to the inner tableView contentSize. You'd avoid doing this extra work by using only one tableView.

**Comment by rlaferla** [comment]
BTW - I've observed that cellForRowAtIndexPath: in  IASKAppSettingsViewController, doesn't reuse cells.  Wouldn't it be better if for each different specifier type, it had a reuse id and reused the cells?

**Comment by rlaferla** [comment]
I think having a fixed tableview height to fit 3-4 rows would be acceptable.   I suppose it would be nice to size the table view to just the # of rows especially if it's only 1-2 rows (with one row being the minimum for "Add record..." row)

**Comment by futuretap** [comment]
Are you sure about the reuse problem? `-tableView:newCellForSpecifier:` calls `-dequeueReusableCellWithIdentifier:` and I verified that it successfully reuses cells.

A fixed tableView height kind of defeats the purpose of the whole feature, imo. What are these empty rows good for? What if the user creates more than 3 accounts? A scrolling tableView inside a scrolling tableView? Would be really ugly imo.

Again, you don't even have all these problems when using a single tableView.

**Comment by rlaferla** [comment]
I didn't see that but yes, it indeed reuses the cells.  

As for the design, I'm just trying to flush out the pros/cons. I agree that it would be better to not have empty rows.  I'm not sure that a scrolling table view within a table view for over say 4 rows is necessarily a bad thing.  In one way, it allows you to see the other sections when there are many rows in the sub/child table.  I see your perspective though.  However, a single table view could have a higher maintenance cost.  Perhaps, we should focus on how to best design it for maintainability.

**Comment by futuretap** [comment]
A scrolling table view within a table view is a bad compromise imo. And multiple scrollviews scrolling in the same direction are a no-go imo. I'm all open to discuss improvements to maintainability but not at the expense of an inferior UI. I think it won't be that unmaintainable if we require an account list to be a dedicated section. Then we simply have to check if the current section is a normal or account list section and react accordingly.

**Comment by rlaferla** [comment]
I agree.  Again, I'm just flushing out pros/cons while I'm prototyping.  I actually have a version that uses child tableviews but without scrollers or empty space.

![image](https://cloud.githubusercontent.com/assets/1135694/10030152/34c7f09a-6144-11e5-91c1-009e49f6ff8f.png)

**Comment by futuretap** [comment]
Another reason to go for one tableView: VoiceOver users can easily swipe through all rows and sections.

**Comment by rlaferla** [comment]
I seem to be able to use VoiceOver just fine.  It doesn't seem to have the issue you're talking about.  Perhaps you can elaborate.

**Comment by futuretap** [comment]
Two-finger swipe down sequentially reads all cells. Might well be that it still works with your approach. 

You seem to be very attached to your approach. I'm not saying that it won't work at all but it's hard to get right in every little detail. However, I'll gladly take a look at your solution.

**Comment by rlaferla** [comment]
I'm really not attached to any implementation.  I do have a prototype but it's just that.  But I must admit that I feel that you're attached to your approach.  ;-)  Seriously, it doesn't really matter but I do want the UI to work well and the code to be relatively easy to follow and maintainable.  If you want to implement it differently, it's really your choice as it's your project.  I just have a need as an app developer and want to help out.  I'd be willing to look at your code implementation/prototype as well.

**Comment by futuretap** [comment]
So if you ask me, let's go with the one-tableView approach. I believe it'll be easier to get the UI right and the maintainability is solvable. However I don't have the capacity right now to develop that feature and I can't keep you from implementing it the way you want! After all, I'm happy to receive contributions at all so I won't dictate a particular approach.

**Comment by futuretap** [comment]
IASK supports this. See [List Groups](https://github.com/futuretap/InAppSettingsKit#list-groups).

**Comment by pke** [comment]
Just to clarify, this would not work in the iOS settings screen, since its not that interactive, would it?

**Comment by futuretap** [comment]
Yes, you’re right.
