### ISSUE TITLE
Swift example for InAppSettingsKit

### ISSUE THREAD

**Issue by realpicky** [futuretap/InAppSettingsKit#296]
This is a selfish request, but since I've only picked up Swift (just started) and not Obj-C I was wondering wether someone could provide a Swift sample of the app which doesn't require understanding Obj-C ? 

PS. Willing to sponsor the work.

**Comment by edasque** [comment]
Hey @realpicky,

which part do you need an example for? I am starting to use InAppSettingsKit with Swift, so I might be able to help.

Erik

**Comment by armanb21** [comment]
@realpicky I'm sure somebody will be able to help. Just create a Obj-C linker flag.

**Comment by edasque** [comment]
@realpicky let me know if you do actually need help as I finished an integration in Swift.

**Comment by realpicky** [comment]
Thanks - Erik I got a developer to do it for me.

Happy to send on the project files if you’re interested.



-- 
Real Picky Gourmet
Sent with Airmail

Am 29. Juni 2015 bei 19:02:48, Erik Dasque (notifications@github.com) schrieb:

@realpicky let me know if you do actually need help as I finished an integration in Swift.

**Comment by armanb21** [comment]
Woah. That is so cool. I can reply to these things over email.

On Mon, Jun 29, 2015 at 7:01 PM, realpicky <notifications@github.com> wrote:

> Thanks - Erik I got a developer to do it for me.
>
> Happy to send on the project files if you’re interested.
>
>
>
> --
> Real Picky Gourmet
> Sent with Airmail
>
>
> Am 29. Juni 2015 bei 19:02:48, Erik Dasque (notifications@github.com)
> schrieb:
>
> @realpicky let me know if you do actually need help as I finished an
> integration in Swift.
>
> —
> Reply to this email directly or view it on GitHub.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/futuretap/InAppSettingsKit/issues/296#issuecomment-116777851>
> .
>



-- 
Thanks,
*A*rman *B*halla
CEO & Founder of The YQPC Group and Virtual Cheddar
armanbhalla6@gmail.com
arman@daccaa.com
**DISCLAIMER**
Note: Privileged/Confidential information may be contained in this message
and may be subject to legal privilege. Access to this e-mail by anyone
other than the intended is unauthorised. If you are not the intended
recipient (or responsible for delivery of the message to such person), you
may not use, copy, distribute or deliver to anyone this message (or any
part of its contents ) or take any action in reliance on it. In such case,
you should destroy this message, and notify us immediately. If you have
received this email in error, please notify us immediately by e-mail or
telephone and delete the e-mail from any computer. If you or your employer
does not consent to internet e-mail messages of this kind, please notify us
immediately. All reasonable precautions have been taken to ensure no
viruses are present in this e-mail. As our company cannot accept
responsibility for any loss or damage arising from the use of this e-mail
or attachments we recommend that you subject these to your virus checking
procedures prior to use. The views, opinions, conclusions and other
informations expressed in this electronic mail are not given or endorsed by
the company unless otherwise indicated by an authorized representative
independent of this message.

**Comment by pizmokid** [comment]
I'm also trying to set this up -- if anyone had a sample project I could take a look at, that'd be awesome...

**Comment by realpicky** [comment]
Send me an email - and I’ll send you a project file


-- 
Real Picky Gourmet
Sent with Airmail

Am 13. August 2015 bei 20:08:41, Gabriel (notifications@github.com) schrieb:

I'm also trying to set this up -- if anyone had a sample project I could take a look at, that'd be awesome...

**Comment by gabrielpjensen** [comment]
thanks @realpicky! I don't see your email publicly listed, but I'm at gabriel@pizmogames.com

**Comment by pizmokid** [comment]
thanks @realpicky! I don't see your email publicly listed, but I'm at gabriel@pizmogames.com

**Comment by futuretap** [comment]
Guys, I think it would be great if we could do this publicly. Judging by this thread, there are a number of users interested in this. So if you could share a sample project publicly (e.g. using a fork) that would be awesome! Unfortunately, I can't allocate time for that personally, right now. However, I'd be glad to incorporate a pull request!

**Comment by realpicky** [comment]
Great - sent you the project directly

-- 
Real Picky Gourmet
Sent with Airmail

Am 13. August 2015 bei 20:21:54, Gabriel (notifications@github.com) schrieb:

thanks @realpicky! I don't see your email publicly listed, but I'm at gabriel@pizmogames.com

**Comment by realpicky** [comment]
I just donated the project to Gabriel  ( I had a guy code it up for me it’s a zip file) 

Use as you wish! (Sorry I’m busy otherwise)

-- 
Real Picky Gourmet
Sent with Airmail

Am 13. August 2015 bei 20:25:09, Ortwin Gentz, FutureTap (notifications@github.com) schrieb:

Guys, I think it would be great if we could do this publicly. Judging by this thread, there are a number of users interested in this. So if you could share a sample project publicly (e.g. using a fork) that would be awesome! Unfortunately, I can't allocate time for that personally, right now. However, I'd be glad to incorporate a pull request!

**Comment by mathieudebrito** [comment]
+1

**Comment by JoeDurand3** [comment]
Was this ever publicly shared? I am having issues importing IASK through my Obj-C bridging header after installing via pods.

**Comment by futuretap** [comment]
Unfortunately not. @pizmokid would you be willing to share the code?

**Comment by realpicky** [comment]
Happy to send project (I had someone over at Fiverr build for me) to whomever want’s it.

Or if someone tells me how this works -I’ll happily upload on github somewhere (it’s a zip file containing a XCode project).



-- 
Real Picky Gourmet
Sent with Airmail

Am 25. April 2016 bei 11:17:34, Ortwin Gentz, FutureTap (notifications@github.com) schrieb:

Unfortunately not. @pizmokid would you be willing to share the code?

**Comment by futuretap** [comment]
Great, send it to gentz @ futuretap dot com and I'll put it on GH.

**Comment by futuretap** [comment]
Here's the repo for the [Swift sample app](https://github.com/futuretap/InAppSettingsKit-Swift-Sample). Note that it doesn't build under the current Xcode since the code isn't yet converted to the latest Swift syntax. I'd welcome a pull request!

**Comment by cpoetter** [comment]
I am also very much looking forward to a 'how to' for the newest swift version

**Comment by AdrenalineAMP** [comment]
@realpicky any chance you still have this project, and would be willing to share? Im at [jrobinson@adrenalineshot.com](jrobinson@adrenalineshot.com)

Thanks!

**Comment by jrobinsonadrenaline** [comment]
@realpicky any chance you still have this project, and would be willing to share? Im at [email](jrobinson@adrenalineshot.com)

Thanks!

**Comment by futuretap** [comment]
In 3.0 I rewrote the sample app in Swift.
