### ISSUE TITLE
Validation?

### ISSUE THREAD

**Issue by rlaferla** [futuretap/InAppSettingsKit#318]
Is there any support for validation?  For in-app settings, it would be nice to have min/max length, regex matching, etc...  At minimum, there should be some sort of validation delegate.

**Comment by futuretap** [comment]
No because it's unclear what to do in case of a validation failure. Reset the control to the previous value? Prevent dismiss/pop with an alert?
However you can listen to kIASKAppSettingChanged notifications and set the value back to a valid value or display an alert. You can also override the dismissal or pop. So essentially you've all the hooks at your disposal to add validation.

**Comment by rlaferla** [comment]
The action shouldn't be provided by the framework.  Just the hooks.  The notification that gets sent out is a bit coarse.  Also, limiting the length (min/max) would need to be done as each character was typed.

**Comment by futuretap** [comment]
IASK 3.0 supports [validation of text fields](https://github.com/futuretap/InAppSettingsKit#validation). Hope that helps!
