### ISSUE TITLE
Table not Reloaded?

### ISSUE THREAD

**Issue by ronyronen** [futuretap/InAppSettingsKit#335]
I used the demo app and pick a value. When returning back the old value still displayed. Scrolled down and up and then it refreshed.

Flow:
Tap Settings -> Update At Launch -> Select any value -> Tap back. Value not changed. Scroll down and up and value changed.

**Comment by ronyronen** [comment]
Moved `[super viewWillAppear:animated]` to bottom at `viewWillAppear:animated` and it's now working.

**Comment by funnel20** [comment]
This is related to the fix for https://github.com/futuretap/InAppSettingsKit/issues/333.
I must admit that I only tested the solution in my app, not anymore in the Sample Project.
I did now, and I can confirm your issue in the Sample Project. However, my own Project works as expected (and solves https://github.com/futuretap/InAppSettingsKit/issues/333).
Really strange.

**Comment by futuretap** [comment]
Grr, I knew that [super viewWillAppear:] change in #333 fix might have side effects… Should work again now.

**Comment by funnel20** [comment]
Thanks, the current solution works for both my Project and the Sample Project, for both #333 and this #335.
