### ISSUE TITLE
System Image Support

### ISSUE THREAD

**Issue by akhiljayaram** [futuretap/InAppSettingsKit#459]
Please add support  for adding icon with system image.

**Comment by futuretap** [comment]
Interesting idea. What exactly are you looking for? In which element would you like to see system image support?

**Comment by akhiljayaram** [comment]
// I just added a hack like this
extension IASKSpecifier
{
    var cellSystemImage: UIImage?
    {
        if let imageName = specifierDict["IASKCellSystemImage"] as? String
        {
            return UIImage(systemName: imageName)
        }
        return nil
    }
}

// and in cell for indexPath add

override func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell
    {
        let cell = super.tableView(tableView, cellForRowAt: indexPath)
        if let specifier = self.settingsReader?.specifier(for: indexPath)
        {
            cell.imageView?.image = specifier.cellSystemImage
        }
        cell.imageView?.tintColor = .label
        return cell
    }

**Comment by pdobrigkeit** [comment]
I would also really like to see this feature. Makes adding premade symbols to the slider for example very easy

**Comment by funnel20** [comment]
@futuretap I'm a fan of SF Symbols, since the benefits are multiple. It creates a consistent and intuitive UI, without having to add tons of images to an App bundle.

It would be very convenient and highly appreciated when you can add support for SF Symbols (see: [`systemImageNamed:`](https://developer.apple.com/documentation/uikit/uiimage/3294233-systemimagenamed)) to your brilliant project.

**Comment by funnel20** [comment]
@futuretap Thank you for implementing this in version 3.6, highly appreciated to get an even more native look and fool of our app settings bundles.

I have added request https://github.com/futuretap/InAppSettingsKit/issues/489 to go a step further with SF Symbol Configuration.
